import type { Metadata } from "next";
import { Glegoo, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar/Navbar";
import Contact from "@/components/Contact/Contact";

const inter = Inter({ subsets: ["latin"] });

const glegoo = Glegoo({
  subsets: ["latin"],
  variable: "--font-glegoo",
  preload: true,
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} >
        <Header/>
        {/* <Navbar/> */}
        {children}
        <Contact/>
        <Footer/>
      </body>
    </html>
  );
}
